sudo: required
services:
    - docker
# before_install:
#     - docker build -t oluwagbenga/react-test -f ./client/Dockerfile.dev ./client 
script:
    - docker run oluwagbenga/react-test npm test -- --coverage  
after_success:
    - docker build -t oluwagbenga/multi-client ./client
    - docker build -t oluwagbenga/multi-nginx ./nginx
    - docker build -t oluwagbenga/multi-server ./server
    - docker build -t oluwagbenga/multi-worker ./worker
 
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    #Take those images and push them to docker hub
    - docker push oluwagbenga/multi-client
    - docker push oluwagbenga/multi-nginx
    - docker push oluwagbenga/multi-server
    - docker push oluwagbenga/multi-worker