sudo: required
services:
  - docker

before_install:
  - docker build -t oluwagbenga/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run oluwagbenga/react-test npm test -- --coverage

after_success:
  - docker build -t oluwagbenga/multi-client ./client
  - docker build -t oluwagbenga/multi-ngins ./nginx
  - docker build -t oluwagbenga/multi-server ./server
  - docker build -t oluwagbenga/multi-worker ./worker

  # Take and push all images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # login through docker cli first
  - docker push oluwagbenga/multi-client
  - docker push oluwagbenga/multi-nginx
  - docker push oluwagbenga/multi-server
  - docker push oluwagbenga/multi-worker


